Users
Kadragow/project-hospital pull request #1
Opened 2020-09-23 21:46 UTC by Barbar980

Creation a user class and inherited from it patient and doctor class.
In the code due references to not existing methods compiler throwing many errors.
Pleas give feedback about created class and new packages.

2020-09-23 22:46 UTC, Kadragow commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
We can use Lombok to generate getters, setter, All args constructor and No args constructor

2020-09-23 22:53 UTC, Kadragow commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
There should be getters and setters for these lists, this may cause some problems

2020-09-23 22:54 UTC, Kadragow commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +    private List<Integer> testInt = new ArrayList<>();
Same here, missing getters and setters

2020-09-23 22:59 UTC, Kadragow requested changes
Generally its fine, but getters and setters have to be added for lists. Also it may be helpful to use Lombok to generate getters, setters and constructors (but it's not necessary!)

2020-09-24 06:17 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
Ok, never beofre used Lombok. I will read about this and I will try change code.

2020-09-24 06:20 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
I suggest to use: "first_name" and "last_name" instead of "name" and "surname". "name" itself can cause ambiguity

2020-09-24 06:22 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
small typo in "Departmen"...?

2020-09-24 06:22 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
I made but i deleted because i didnt have any idead how we will can use this list in getter and setter.
Today i will make changes and reupload code.
Did my implementations of addSpecialisations, removeSpecialisation for every list is correct?

2020-09-24 06:24 UTC, Barbar980 commented
Ok, thanks for review.
Today i will return with new code.

2020-09-24 06:33 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
Ok, i was suggested variable named used in Trello.
Can I use insted firstName etc?

2020-09-24 06:34 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
Getter and Setter for the lists looks the same like for other types. In getter you return the list, and in setter you assign the list passed as the paramater. Thats it. Also "Specializations" should be in singular. IMHO In removeSpeecializations we should use different method: remove(Object o) instead of remove(int index)

2020-09-24 06:40 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
> small typo in "Departmen"...?

You have right, i will change this.

2020-09-24 06:49 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<Integer> test = new ArrayList<>();;
> Getter and Setter for the lists look the same like for other types. In Getter you return the list, and in setter you assign the list passed as the paramater. That's it. Also "Specializations" should be in singular form. IMHO In removeSpeecializations we should use different method: remove(Object o) instead of remove(int index)

I dont even thinked about it but this is obvious. This is how look codding at 11pm...
I will replace this code used in list.

2020-09-24 06:50 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +    private List<Integer> testInt = new ArrayList<>();
Like above, i will change this asap.

2020-09-24 06:59 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
yes, you should I always mistake all this naming conventions

2020-09-24 07:01 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
Ok, I prefer "frstName" than "first_name". First in my opinnion look more better. I dont know how this case look in real job

2020-09-24 07:31 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
this is Java, so camelCase convention is used

2020-09-24 13:39 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +public class Doctor extends User {
Test

2020-09-24 13:43 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Date entryDate;
test

2020-09-24 13:45 UTC, Barbar980 commented on src/main/java/it/arcade/hospital/user/User.java
> +package it.arcade.hospital.user;
t

2020-09-25 09:03 UTC, Kadragow approved these changes
Ok

2020-09-25 18:33 UTC, droanna commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +}
I think that methods like adding or removing shouldn't be included in models

2020-09-25 18:39 UTC, droanna commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
These fields don't have to be initialised.

2020-09-26 09:03 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +}
In fact, that is Repository layer job.

2020-09-26 09:05 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
They doesn't have to, but doing so is a way to prevent from NullPointerException

2020-09-26 10:02 UTC, droanna commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
Yes, but other fields (object types as well) aren't initialised either, so I think it should be consequent. And initialisation with particular type (ArrayList) hier I think is not very good pattern.

2020-09-26 10:06 UTC, droanna commented
I think that there should be added too:
1. Annotations
2. Hashcode/equals methods

2020-09-26 10:19 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
Do you that, that LinkedList would be better in our case?

2020-09-26 10:23 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    }
Is this constructor really necessary? Is it possible to create doctor without create new user underneath it?

2020-09-26 11:14 UTC, droanna commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
Ok, so let it be. I would not put it into the constructor. Regarding list type of course ArrayList (as almost always).

2020-09-26 14:12 UTC, zawiszaty commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +}
if you follow domain driven design should be

2020-09-26 14:16 UTC, zawiszaty commented on src/main/java/it/arcade/hospital/user/User.java
> +public class User {
I don't know if this class is necessary, because this create unnecessary abstraction layer in doctor and patient class.  Maybe you should remove Patient(every user can be patient) and connect doctor model with user by `many to one` relation(Many user can have access to doctor, because they can have secretary or whatever).

2020-09-26 17:15 UTC, rwedzony commented
> I think that there should be added too:
> 
> 1. Annotations
> 2. Hashcode/equals methods

Ad1-true, Ad2-> Why you want to add these methods? Do we plan to compare objects somehow?

2020-09-26 17:35 UTC, droanna commented
I think that there should be added too:

Annotations
Hashcode/equals methods
Ad1-true, Ad2-> Why you want to add these methods? Do we plan to compare objects somehow?

I think it's standard procedure. If it would be necessary to compare two objects, it's better to have these methods proper overwritten than to remember about their addtion. Furthermore other methods use equals to compare objects too.

2020-09-27 18:57 UTC, rwedzony commented
> I think that there should be added too:
> 
> Annotations
> Hashcode/equals methods
> Ad1-true, Ad2-> Why you want to add these methods? Do we plan to compare objects somehow?
> 
> I think it's standard procedure. If it would be necessary to compare two objects, it's better to have these methods properly overwritten than to remember about their addtion. Furthermore other methods use equals to compare objects too.

It is just opossite, this is not standard procedure. It is realy bad idea to overwrite equals  and hashcode methods if you do not have to. Why so? Because wrong implementations of equals and hashcode methods can cause serious troubles, when you use collections like HashMap and HashSet. If you REALLY need to compare objects you implement Comparable interface, which is more safe and robust, than playing with built-in methods. "Furthermore other methods use equals to compare objects too" - which methods? Will we use them? Will we ever compare two patients, two doctors, two users in any our scenario? No. And according to Lombok docu: It is tricky situation when you use auto generated Hashcode and Equals to class that extends other one,and it needs special treatment. So better to remove it completely.

2020-09-27 20:45 UTC, droanna commented
> > I think that there should be added too:
> > Annotations
> > Hashcode/equals methods
> > Ad1-true, Ad2-> Why you want to add these methods? Do we plan to compare objects somehow?
> > I think it's standard procedure. If it would be necessary to compare two objects, it's better to have these methods properly overwritten than to remember about their addtion. Furthermore other methods use equals to compare objects too.
> 
> It is just opossite, this is not standard procedure. It is realy bad idea to overwrite equals and hashcode methods if you do not have to. Why so? Because wrong implementations of equals and hashcode methods can cause serious troubles, when you use collections like HashMap and HashSet. If you REALLY need to compare objects you implement Comparable interface, which is more safe and robust, than playing with built-in methods. "Furthermore other methods use equals to compare objects too" - which methods? Will we use them? Will we ever compare two patients, two doctors, two users in any our scenario? No.

If you're so sure that it's not necessary then ok. I agree that not proper overwriting can cause serious problems, but not overwriting and comparing references as well. And which methods; e.g. contains() method from java.util.ArrayList<E>

2020-10-02 18:02 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    private List<MedicalRecord> medicalRecordList = new ArrayList<>();
I'm for initializing lists to empty objects, I would recommend everybody to do so. It may prevent NullPointerExceptions. Lists/Maps etc should not be null.

2020-10-02 18:06 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    }
@rwedzony yes, constructors are preferred way of constructing objects. It's spring that doesn't require it and because of it young programmers tend to think they are unnecessary. 
If you don't like writing constructors, I suggest Lombok `@Value` or `@Data` annotations along with `@RequiredArgsConstrucor` or if you don't do immutability `@NoArgsConstructor`.

Please also see other arguments, ex: https://www.youtube.com/watch?v=0FsO92obwV0

2020-10-02 18:19 UTC, rwedzony commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    }
@Augustyn I am pretty sure you don't know what I was asking for. I was not discusing wheather constructors are generally necessary, because of course there are. The keywords here is THIS constructor. Doctor extends User, so when you create Doctor you have to call super constructor somehow. Constructor without super call is useless, that was my point. So maybe first try to understand what is going on, before you start to comment.

2020-10-02 18:25 UTC, Augustyn commented
> It is realy bad idea to overwrite equals and hashcode methods if you do not have to. Why so? Because wrong implementations of equals and hashcode methods can cause serious troubles, when you use collections like HashMap and HashSet.

Yes, if you do it badly, it will cause serious performance problems in collections using hash. And no: it should be implemented. Using default implementation may break contract, as it is JVM instance dependent (And oracle is not only JDK provider. There are many, many others: Amazon, Azul, OpenJDK, and other). And java contract says: hashcode should be implemented in such way, that object stored in disc, and read from disc would have the same hashcode. This may not be the case if you persist object to cache (serialize it) and deserialize it using different JVM.
There's another reason to implement hashCode and equals, and that is if you want to compare objects based on different set of fields then all fields.That's the case with hibernate. Objects persisted by hibernate have their ID field that is considered by hibernate as a object identifier. Two objects are the same (by hibernate) if they have the same id. It does not matter to hibernate what are other fields values. It's ID that counts to determine if object should be persist in place of existing one in database, and other fields will be updated, amended, removed etc based on what happen. But only one field counts for hibernate to determine which row in database should be changed.

So, the only way is: not do it badly. Use Lombok `@EqualsAndHashCode`, use [apache commons HashCodeBuilder](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/builder/HashCodeBuilder.html)

2020-10-02 20:03 UTC, Augustyn commented on src/main/java/it/arcade/hospital/medicalrecord/MedicalRecordService.java
> +        }catch (Exception e){
formatting: try space curly braces.
Why you catch exception to throw exception and annotate method that it throws exceptions? 
Will without it won't throw exception? You are forcing developers to write boiler code (something may fail, d'ooohhh!) that has no business meaning (exception not business specific) and tell nothing about nature of problem)

2020-10-03 07:18 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/doctor/Doctor.java
> +    }
My bad, I didn't understand what you mean. And it's a good chance that your suggestion will miss inexperienced programmer as well.
Yes, there might be the case, where we don't need data that is in superclass. As much there is such possibility, I don't think that this is the case. Doctor without surname or at least ID would be unidentifiable by the system. This constructor should be removed in favour of one that have full set of data, or parameter list extended to level that will allow of identifying such medic. I would be for removal of this constructor, there's another one with full set of data.

2020-10-03 07:21 UTC, Augustyn commented on src/main/java/it/arcade/hospital/medicalrecord/MedicalRecordService.java
> +    public MedicalRecord saveMedicalRecord(MedicalRecord medicalRecord) throws Exception{
It is bad practice declare that method,class or anything throws 'Exception'. It is obvious that something may go wrong, and you don't have to declare it. Especially that this is checked exception makes using lambdas more difficult. Since Java 8 it is better to throw unchecked exceptions.

2020-10-03 07:22 UTC, Augustyn commented on src/main/java/it/arcade/hospital/role/Role.java
> +    @Column(name = "id")
"name" parameter is not required. This is default: column name will have the same name as variable name.

2020-10-03 07:24 UTC, Augustyn commented on src/main/java/it/arcade/hospital/role/Role.java
> +    @Column(name = "role_name")
I think that this is not required as well. Column name by default will be changed from camel case notation to underscore notation by hibernate, but I may be wrong with this. Please check.

2020-10-03 07:25 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/User.java
> +    private Long id;
It might be good idea, to create abstract base entity class with only this field, and extend that class. This way you will save some repetition, that all `@Entity` classes have.

2020-10-03 07:27 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/User.java
> +    @GeneratedValue(strategy=GenerationType.TABLE)
Why all sudden GenerationType is TABLE. Every other entity I (so far) sow here had AUTO. What's the difference?
I'm not saying that this is wrong, but please explain what's the difference between AUTO and TABLE.

2020-10-03 07:29 UTC, Augustyn commented on src/main/java/it/arcade/hospital/user/patient/Patient.java
> +    private String pesel;
You can add some constraints to this field. We know, that it's size is fixed. This may prevent inserting fault data to database.

2020-10-03 07:36 UTC, Augustyn commented on src/main/resources/sql_scripts/schema.sql
> +                                                                          'jnowak@wp.pl',
I would be cautious here. This for sure is someone mail. When there will be functionality of sending emails for patients this will cause that poor guy will be spamed by example application.
As a example data I would go for 'example.com' domain that is exclusivity for this purpose. No human can have 'example.com' mail. It is controlled by USA and the country prevent humans from having real emails at this domain.

2020-10-03 08:06 UTC, Augustyn commented on src/main/resources/sql_scripts/schema.sql
> +                                                                          'zchytry@klinika.pl',
Domain "klinika.pl" is registered in home.pl. There's a chance that you are using real email address, OR it will be real address in future. Please use domain or subdomain of 'example.com'. ex. 'linic.example.com' to distinguish from patients, etc.

2020-10-26 20:26 UTC, merged