Offer_model_repository_service
Kadragow/project-hospital pull request #4
Opened 2020-09-27 18:11 UTC by droanna

2020-09-27 19:08 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferRepository.java
> +@RepositoryRestResource(collectionResourceRel = "offers", path = "offers")
Why did you use RepositoryRestResourse?

2020-09-27 19:10 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	public Offer saveOrUpdateOffer(Offer offer) {
Why do you return saved/ updated offer?

2020-09-27 19:34 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
Did you test this code if it is working?

2020-09-27 19:35 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +		}
You break the DRY rule.

2020-09-27 20:16 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferRepository.java
> +@RepositoryRestResource(collectionResourceRel = "offers", path = "offers")
Why not? Is it better to use @Repository?

2020-09-27 20:21 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	public Offer saveOrUpdateOffer(Offer offer) {
As far as I know there are 3 approaches:
- to make it as a void method
- to return id of new object
- to return saved object
So, I chose this 3. one, but it's not something I will insist on.

2020-09-27 20:22 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
I will test it when other required classes will be added.

2020-09-27 20:23 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +		}
You're right. I will correct it.

2020-09-27 21:09 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferRepository.java
> +@RepositoryRestResource(collectionResourceRel = "offers", path = "offers")
None of these is "better" or "worse". The question should be rather which one will fulfill our requirements. To give you quick overview: https://www.youtube.com/watch?v=sCMFoqdpRns&ab_channel=KindsonTheTechPro

2020-09-27 21:15 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	public Offer saveOrUpdateOffer(Offer offer) {
Thats true. But try to think about consequences of your choice. Will this object be somewhere necessary?

2020-09-27 21:19 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
I asked, because IMHO this will end with SQL exception.

2020-09-28 09:51 UTC, zawiszaty commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	public Offer saveOrUpdateOffer(Offer offer) {
if you have `or` in method name, its mean that it should be 2 methods :P

2020-09-29 17:26 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
Taking into consideration how save() works it won't, but in fact, implementation of this method here is not needed at all.

2020-09-29 20:41 UTC, rwedzony commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
What you was doing here was following: You have offer as function parameter. You check if Id exist (It means or is it a new offer, or is it the old one updated). If id != null, it means that it is old offer, but updated. You search for this offer and assigning to optional foundOffer. If it is present ( so it means you found offfer with given Id) there comes the tricky part: instead of modyfing OLD reference, you create NEW offer with the same id like already stored in DB. So basically you try to save new object to DB with Id that already exitst. That will result with SQL Exception, or maybe with duplicated object, I am not pretty sure now, but for sure it is not intended. And generally save method is necessarly-> how would you you call save from controller layer, when you do not have "save" in service layer?

2020-09-29 22:01 UTC, droanna commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
Service layer is not obligatory, it contains additional logic, which is not supported by repository layer. I can use JPARepository/CRUDRepository methods directly from controller, when any additional logic is added, like using save() method to insert/update operations in this case.

2020-10-02 17:57 UTC, Augustyn requested changes

2020-10-02 17:57 UTC, Augustyn commented on pom.xml
> +			<version>2.3.3.RELEASE</version>
Please move version to properties. It would be easier to manage dependencies version this way.

2020-10-02 17:57 UTC, Augustyn commented on pom.xml
> +	<properties>
Please add variables thanks to which build would be system independent: 
- file encoding (property: project.build.sourceEncoding )
- configure maven source/target version, you can reuse "java.version" property: `maven.compiler.source` and `maven.compiler.source`

2020-10-02 17:57 UTC, Augustyn commented on pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Please don't format whole files, unless you have new code formatter and just shared it to everyone.

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/Offer.java
> +	@ManyToOne(fetch = FetchType.LAZY)
`LAZY` is hibernates default. You don't have to provide it

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/Offer.java
> +	Long id;
Please add private modifier to be more compliment with SOLID (letter O)

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/Offer.java
> +    @JoinColumn(name = "id_department")
Formatting....

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	@Autowired
It's redundant. It will work without this annotation. +1 for constructor dependency injection.

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +		return isEmpty(offers) ? new ArrayList<Offer>() : offers;
This logic:
- check if List is empty. If it is empty, return empty list. If not, return this list...
Does it sound OK to you? Why returning different empty list if we already have empty list?  

```suggestion
		return offerRepository.findAllByDepartment(department);

```

2020-10-02 17:57 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +		return isEmpty(offers) ? new ArrayList<Offer>() : offers;
as above
```suggestion
		return offerRepository.findAllByName(name);

```

2020-10-04 11:24 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +	public Offer saveOrUpdateOffer(Offer offer) {
It may be expected by Front-end. It's rather good practice IMHO to return what was stored. I'm for it :+1:

2020-10-04 16:18 UTC, Augustyn commented on pom.xml
> +		<thymeleaf.version>3.0.11.RELEASE</thymeleaf.version>
This won't change version used by spring. You have to add:
`<version>${thymeleaf.version}</version>` to as line 72, that you just removed.
In the same way you can have one variable for JDK version, reuse `${java.version}` as a value in lines : 19 and 20.

2020-10-04 16:39 UTC, Augustyn commented on src/main/java/it/arcade/hospital/offer/OfferService.java
> +				Offer updatedOffer = new Offer(foundOffer.get().getId(), offer.getName(), offer.getPrice(), offer.getDepartment());
> Service layer is not obligatory, it contains additional logic, which is not supported by repository layer. 

As much as this is true, and even 15 years ago developers created SQL queries from JSP files (seen it) this is not recommended practice. Such mix of responsibilities, makes it harder to change components, as there's too strong coupling between presentation layer and database. If you ever want to change either it would be digging through whole application and changing everything. That's why concept of layers emerged. It pushes responsibilities to one place.
It may not be required now, but in the future, there for sure will be need to add additional logic and having prepared layer for that wouldn't make anyone wonder where to add it.
Furthermore as it is now considered best practice, application without it would look unprofessional.

2020-10-04 16:41 UTC, Augustyn commented on pom.xml
> +		<thymeleaf.version>3.0.11.RELEASE</thymeleaf.version>
And it's missing property `project.build.sourceEncoding`. Windows by default is using CP1250, other normal systems: UTF-8. This property ensures that build will be system independent (always used one encoding, from configuration).

2020-10-26 20:27 UTC, merged